### ISSUE TITLE
Copiar objeto não copia objeto com mesmas propriedades

### ISSUE THREAD

**Issue by emanueles** [danilob/SceneBuild#2]
Quando eu copio um cubo com Ctrl + C, ele adiciona um cubo com dimensões e material diferentes do cubo original. Por exemplo, copiei o cubo cor de uva e ele adicionou o cubo verde pequeno.

![screenshot from 2015-05-21 10 27 19](https://cloud.githubusercontent.com/assets/2118994/7749457/09760186-ffa4-11e4-8924-db79d7b48a22.png)

**Comment by danilob** [comment]
A copia é realizada quando o objeto selecionado está no modo object, fiz
uns testes aqui e clonou normalmente... depois me envie esta cena para que
eu posssa testá-la.

Em 21 de maio de 2015 10:29, Emanuele Santos notifications@github.com
escreveu:

> Quando eu copio um cubo com Ctrl + C, ele adiciona um cubo com dimensões e
> material diferentes do cubo original. Por exemplo, copiei o cubo cor de uva
> e ele adicionou o cubo verde pequeno.
> 
> [image: screenshot from 2015-05-21 10 27 19]
> https://cloud.githubusercontent.com/assets/2118994/7749457/09760186-ffa4-11e4-8924-db79d7b48a22.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/danilob/SceneBuild/issues/2.

## 

---

--- Danilo Borges da Silva
--- (86) 9949 4681

**Comment by emanueles** [comment]
Danilo, que versão de Qt você usa? Está acontecendo o mesmo problema no meu desktop. Em ambos uso a versão 5.4.1 do Qt.

**Comment by emanueles** [comment]
Eu acho que o problema era porque no menu principal também tinha definido CTRL+C como atalho para criar um cubo e esse era sempre disparado antes. Depois que removi a função clone voltou a funcionar.
